language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run clean-force
  - npm run remove-modules
  - npm run install-npm
  - npm run audit-fix

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $frontend-kawal-corona
  project: ./build/
  local_dir: build
  on:
    branch: master