export const FETCH_INDONESIA = 'FETCH_INDONESIA';
export const FETCH_PROVINSI = 'FETCH_PROVINSI';
export const FETCH_PAPUA = 'FETCH_PAPUA';
export const FETCH_GLOBAL = 'FETCH_GLOBAL';
export const FETCH_INFOGRAFIK = 'FETCH_INFOGRAFIK';
export const FETCH_RUMAHSAKIT = 'FETCH_RUMAHSAKIT';